name: Validate build environment
description: Validates environment passed to a build workflow
inputs:
  ENV:
    description: Environment string to validate
    required: true
  PLATFORM:
    description: The platform to build
    required: true
outputs:
  IS_VALID:
    description: Is the environment valid?
    value: ${{ fromJSON(steps.validatePlatform.outputs.IS_VALID) && fromJSON(steps.validateEnv.outputs.IS_VALID) }}
runs:
  using: composite
  steps:
    - id: validatePlatform
      run: echo "IS_VALID=${{ contains(fromJSON('["android"]'), inputs.PLATFORM) }}" >> "$GITHUB_OUTPUT"
      shell: bash

    - id: validateEnv
      run: |
        if [[ ${{ inputs.PLATFORM }} == 'android' ]]; then
          echo "IS_VALID=${{ contains(fromJSON('["beta", "production", "build_internal", "build_e2e"]'), inputs.ENV) }}" >> "$GITHUB_ENV"
        else
          echo "IS_VALID=${{ contains(fromJSON('["beta", "production", "build_internal"]'), inputs.ENV) }}" >> "$GITHUB_ENV"
        fi
      shell: bash
