name: Build desktop app

on:
  workflow_call:
    inputs:
      ENV:
        description: The environment to build for. Must be one of ("staging", "production", "ad-hoc")
        required: true
        type: string

concurrency:
  group: build-android-${{ inputs.ENV }}
  cancel-in-progress: ${{ inputs.ENV == "ad-hoc" }}

jobs:
  buildWeb:
    name: Build desktop app
    runs-on: ubuntu-latest-xl
    steps:
      - id: validateEnv
        run: |
          if [[ ${{ contains(fromJSON('["staging", "production", "ad-hoc"]'), inputs.ENV) }} == 'true' ]]; then
            echo "Environment ${{ inputs.ENV }} is valid for iOS"
          else
            echo "Environment ${{ inputs.ENV }} is not valid for iOS."
            exit 1
          fi

      - uses: actions/checkout@v3

      - name: Create .env.adhoc file based on staging
        if: inputs.ENV == 'ad-hoc'
        run: |
          cp .env.staging .env.adhoc
          sed -i 's/ENVIRONMENT=staging/ENVIRONMENT=adhoc/' .env.adhoc
          echo "PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER" >> .env.adhoc

      - name: Decrypt Developer ID Certificate
        run: cd desktop && gpg --quiet --batch --yes --decrypt --passphrase="$DEVELOPER_ID_SECRET_PASSPHRASE" --output developer_id.p12 developer_id.p12.gpg
        env:
          DEVELOPER_ID_SECRET_PASSPHRASE: ${{ secrets.DEVELOPER_ID_SECRET_PASSPHRASE }}

      - uses: Expensify/App/.github/actions/composite/setupNode@main

      - name: Configure AWS Credentials
        uses: Expensify/App/.github/actions/composite/configureAwsCredentials@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run desktop build
        run: |
          if [[ ${{ inputs.ENV }} == 'ad-hoc' ]]; then
            npm run desktop-build-adhoc -- --publish always
          elif [[ ${{ inputs.ENV }} == 'staging' ]]; then
            npm run desktop-build-staging -- --publish always
          else
            npm run desktop-build -- --publish always
          fi
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload DMG as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: NewExpensify.dmg
          path: desktop-build/NewExpensify.dmg

      - name: Post a message in slack if the build fails
        if: failure()
        uses: Expensify/App/.github/actions/composite/announceFailedWorkflowInSlack@main
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
