name: Build Android app

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:
  buildAndroid:
    name: Build Android app
    runs-on: ubuntu-latest-xl
    steps:
      - uses: actions/checkout@v3

      - uses: Expensify/App/.github/actions/composite/validateBuildEnvironment@main
        with:
          PLATFORM: android
          ENV: ${{ inputs.ENV }}

      - uses: Expensify/App/.github/actions/composite/setupNode@main

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Decrypt keystore
        run: cd android/app && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output my-upload-key.keystore my-upload-key.keystore.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Decrypt json key
        run: cd android/app && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output android-fastlane-json-key.json android-fastlane-json-key.json.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Set version in ENV
        run: echo "VERSION_CODE=$(grep -o 'versionCode\s\+[0-9]\+' android/app/build.gradle | awk '{ print $2 }')" >> "$GITHUB_ENV"

      - name: Run Fastlane build
        run: bundle exec fastlane ${{ inputs.ENV }}
