name: Build iOS App

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        description: The name of the workflow artifact where the APK should be uploaded
        required: true
        type: string
      ENV:
        description: The environment to build for. Must be one of ("release", "ad-hoc")
        required: true
        type: string

jobs:
  buildIOS:
    name: Build iOS app
    runs-on: macos-12-xl
    steps:
      - id: validateEnv
        run: |
          if [[ ${{ contains(fromJSON('["release", "ad-hoc"]'), inputs.ENV) }} == 'true' ]]; then
            echo "Environment ${{ inputs.ENV }} is valid for iOS"
          else
            echo "Environment ${{ inputs.ENV }} is not valid for iOS."
            exit 1
          fi

      - uses: actions/checkout@v3

      - uses: Expensify/App/.github/actions/composite/setupNode@main

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install cocoapods
        uses: nick-invision/retry@0711ba3d7808574133d713a0d92d2941be03a350
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: cd ios && bundle exec pod install

      - name: Decrypt profile
        run: cd ios && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output chat_expensify_appstore.mobileprovision chat_expensify_appstore.mobileprovision.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Decrypt certificate
        run: cd ios && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output Certificates.p12 Certificates.p12.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Decrypt App Store Connect API key
        run: cd ios && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output ios-fastlane-json-key.json ios-fastlane-json-key.json.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Run Fastlane build
        run: |
          if [[ ${{ inputs.ENV }} == "release" ]]; then
            bundle exec fastlane ios build
          else
            bundle exec fastlane ios build_internal
          fi

      - name: Upload API as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.ARTIFACT_NAME }}.api
          # Note: this output comes from inside the Fastfile
          path: ${{ steps.build.outputs.IPA_PATH }}

      - name: Upload iOS sourcemaps
        uses: actions/upload-artifact@v3
        with:
          name: ios-sourcemap
          path: main.jsbundle.map

      - name: Post a message in slack if the build fails
        if: failure()
        uses: Expensify/App/.github/actions/composite/announceFailedWorkflowInSlack@main
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
