name: Verify Podfile

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]

jobs:
  verify:
    if: github.actor != 'OSBotify'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install bundler
        run: |
          bundle config path vendor/bundle
          gem install bundler

      - name: Install gems
        run: bundle install

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install node packages
        uses: nick-invision/retry@7c68161adf97a48beb850a595b8784ec57a98cbb
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: npm ci

      - name: Install pods
        run: cd ios && bundle exec pod install
      
      - name: Debug
        run: pwd && ls && pod ipc spec ./node_modules/react-native-webview/react-native-webview.podspec

      - run: ./.github/scripts/verifyPodfile.sh
